### PR TITLE
Add simple performance test for JFM compared with Java File IO

### PR DESCRIPTION
**Pull request by ligangty**

### CODE REVIEW

**Comment by jdcasey** [comment]
retest this please

**Comment by ligangty** [comment]
@jdcasey I've checked the CI build log yesterday, and found that in CI env the JoinableFileManager writing is slower more than 10 times than normal java File IO, which caused the test failing. In my local env, it is less than 3 times. Not sure if this is related to environment.

**Comment by ligangty** [comment]
retest this please

**Comment by jdcasey** [comment]
retest this please

**Pull request merged**
