### PR TITLE
Remove reentrantlock when the fileEntry is removed

### PR DESCRIPTION
**Pull request by ruhan1**
This is to remove the un-used locks to avoid memory issue.

### CODE REVIEW

**Review by jdcasey — APPROVED** [review]
Looks pretty good, but I wonder how hard it will be to merge with the new code on master?

**Comment by ruhan1** [comment]
I would suggest we use this approach. And disable the sweeping thread for now (but keep the code for awile). I will try to merge it.

**Comment by jdcasey** [comment]
@ruhan1 seems like the sweep thread won't interfere with this...so I'm not sure we'd need to disable it

**Comment by ruhan1** [comment]
If that is the case, I will try to keep both code.

**Comment by jdcasey** [comment]
I'd like us to use the SignallingLocker if possible, so we can consolidate the logic we're using around ReentrantLock. It would be a good long-term project to try to consolidate Locker and SignallingLocker, in Indy...but not a high priority for now.

**Comment by ruhan1** [comment]
All right.

**Pull request merged**
